import { Link } from 'react-router-dom';
import { PageShell } from '@/components/PageShell';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { EcosystemLogo, type EcosystemKey } from '@/components/EcosystemLogo';
import { ManagedContentSections } from '@/components/ManagedContentSections';
import { useManagedHero } from '@/hooks/useManagedHero';
import { ArrowRight, Cloud, Cog, Lightbulb, ShieldCheck, Headphones, Sparkles, Users, GraduationCap, Building2, BriefcaseBusiness, HeartHandshake, Landmark, ChevronDown } from 'lucide-react';

type Service={name:string;href:string;logo:EcosystemKey;image:string;desc:string;cta:string};
const pillars:{title:string;subtitle:string;tone:string;icon:typeof Cloud;services:Service[]}[]=[
 {title:'Digital Services',subtitle:'Connecting People. Enabling Possibilities.',tone:'from-blue-700 to-sky-500',icon:Cloud,services:[
  {name:'IHLink DataSub',href:'/datasub',logo:'datasub',image:'/images/mobile-payment.jpg',desc:'Airtime · Data · Bills · TV · Utilities',cta:'Explore DataSub'},
  {name:'SchoolPro by IHLink',href:'/schoolpro',logo:'schoolpro',image:'/images/digital-classroom.jpg',desc:'Education · Management · Results · Communication',cta:'Explore SchoolPro'},
  {name:'IHLink Hosting & Domains',href:'/host',logo:'host',image:'/images/network-engineer.jpg',desc:'Domains · Hosting · SSL · Digital Infrastructure',cta:'Explore Hosting'}]},
 {title:'Technology & Engineering',subtitle:'Ideas. Development. Real Impact.',tone:'from-emerald-700 to-green-500',icon:Cog,services:[
  {name:'IHLink Consult',href:'/consult',logo:'consult',image:'/images/software-consulting.jpg',desc:'Strategy · Technology · IT Solutions · Cloud · AI',cta:'Explore Consult'},
  {name:'IHLink Engineering',href:'/engineering',logo:'engineering',image:'/images/robotics-engineering.jpg',desc:'Control · Robotics · IoT · Instrumentation',cta:'Explore Engineering'}]},
 {title:'Business & Innovation Centre',subtitle:'Create. Print. Learn. Innovate.',tone:'from-orange-600 to-amber-500',icon:Lightbulb,services:[
  {name:'IHLink Print & Branding',href:'/print',logo:'print',image:'/images/tech-team.jpg',desc:'Print · Design · Brand · Promote',cta:'Explore Print'},
  {name:'IHLink 3D & Fabrication Lab',href:'/fabrication',logo:'fabrication',image:'/images/robotics-engineering.jpg',desc:'Prototype · 3D Printing · CAD Design',cta:'Explore 3D Lab'},
  {name:'IHLink AI & Compute',href:'/compute',logo:'compute',image:'/images/software-consulting.jpg',desc:'Compute · AI · Data Science · Research',cta:'Explore AI & Compute'},
  {name:'IHLink Academy',href:'/academy',logo:'academy',image:'/images/digital-classroom.jpg',desc:'Learn · Skill · Grow · Certification',cta:'Explore Academy'}]}
];
const audiences=[[Users,'Individuals','Everyday digital and technology services'],[GraduationCap,'Students','Learn, build and grow'],[Building2,'Schools','Education and management solutions'],[BriefcaseBusiness,'Businesses','Technology and tools for growth'],[HeartHandshake,'NGOs','Solutions for community impact'],[Landmark,'Government','Institutional technology solutions']] as const;
const faqs=[
 ['What is IHLink?','IHLink Co. Ltd. is one ecosystem bringing together digital services, technology and engineering, and business and innovation services.'],
 ['Do I need separate accounts for each IHLink service?','No. My IHLink is designed around one identity, with access limited to the services authorized for your account.'],
 ['Can I request a quotation before ordering?','Yes. Services that require specification, design or engineering review can use a quotation workflow before payment or production.'],
 ['How do I get support?','Use the Support or Contact pages to reach the appropriate IHLink service team and track your request.']
];
export function CorporateHome(){const hero=useManagedHero('corporate');return <PageShell>
<section className="relative overflow-hidden bg-navy-900 text-white"><div className="absolute inset-0"><img src="/images/tech-team.jpg" alt="" className="h-full w-full object-cover opacity-35"/><div className="absolute inset-0 bg-gradient-to-r from-navy-900 via-navy-900/80 to-navy-900/25"/></div><div className="relative max-w-[1440px] mx-auto px-6 lg:px-10 py-16 lg:py-24 grid lg:grid-cols-2 gap-10 items-center"><div><Badge className="bg-white/10 text-white border-white/20 mb-5"><Sparkles className="w-3 h-3 mr-1"/>Welcome to IHLink Co. Ltd.</Badge><h1 className="text-4xl md:text-5xl lg:text-6xl font-extrabold leading-[1.05]">{hero?.title||'One Ecosystem. Many Solutions. A Brighter Tomorrow.'}</h1><p className="mt-6 text-lg text-blue-100 max-w-2xl">{hero?.body||'Integrated technology, education, digital services, engineering and business solutions for individuals, schools, businesses and communities.'}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#divisions"><Button size="xl" rightIcon={<ArrowRight className="w-5 h-5"/>}>Explore Our Divisions</Button></a><Link to="/contact"><Button size="xl" variant="secondary" className="bg-white text-navy-900">Contact Us</Button></Link></div></div><div className="hidden lg:block rounded-3xl overflow-hidden border border-white/20 shadow-2xl"><img src="/images/tech-team.jpg" alt="People collaborating with technology" className="aspect-[4/3] w-full object-cover"/></div></div></section>
<section id="divisions" className="max-w-[1440px] mx-auto px-6 lg:px-10 py-14"><div className="text-center mb-9"><p className="text-sm font-bold uppercase tracking-widest text-royal-600">One company. Three divisions.</p><h2 className="mt-2 text-3xl lg:text-4xl font-extrabold">Explore the IHLink ecosystem</h2><p className="mt-3 text-muted">Each division brings together specialist platforms for a clear, connected customer experience.</p></div><div className="space-y-6">{pillars.map(p=>{const Icon=p.icon;return <section key={p.title} className="rounded-3xl overflow-hidden border border-border bg-white shadow-card"><div className={`bg-gradient-to-r ${p.tone} text-white p-5 flex gap-3 items-center`}><div className="w-12 h-12 rounded-xl bg-white/95 p-1 overflow-hidden shrink-0"><img src={'/brand/ihlink-icon.png?v=20260928-valid-logo4'} alt="" className="w-full h-full object-contain"/></div><div><h3 className="text-xl font-extrabold">{p.title}</h3><p className="text-sm text-white/85">{p.subtitle}</p></div></div><div className={`grid gap-4 p-4 md:p-5 ${p.services.length===2?'md:grid-cols-2':p.services.length===4?'md:grid-cols-2 xl:grid-cols-4':'md:grid-cols-3'}`}>{p.services.map(s=><Link key={s.name} to={s.href} className="group rounded-2xl border border-border overflow-hidden hover:shadow-float transition-all h-full flex flex-col"><div className="aspect-[16/9] bg-slate-100 overflow-hidden"><img src={s.image} alt="" loading="lazy" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"/></div><div className="p-4 flex-1 flex flex-col"><EcosystemLogo service={s.logo} /><p className="mt-2 text-xs text-muted">{s.desc}</p><span className="mt-auto pt-3 inline-flex items-center gap-1 text-sm font-bold text-royal-600">{s.cta}<ArrowRight className="w-4 h-4"/></span></div></Link>)}</div></section>})}</div></section>

<section className="bg-surface border-y border-border"><div className="max-w-[1440px] mx-auto px-6 lg:px-10 py-14"><div className="text-center"><Badge>How It Works</Badge><h2 className="mt-3 text-3xl font-extrabold">One ecosystem, simple access</h2></div><div className="mt-8 grid md:grid-cols-3 gap-4">{[['1','Choose a division','Start with Digital Services, Technology & Engineering, or Business & Innovation.'],['2','Select a platform','Open the specialist IHLink product or service that matches your need.'],['3','Manage in My IHLink','Use your IHLink identity to access authorized services, activity and support.']].map(([n,t,d])=><div key={n} className="rounded-2xl bg-white border border-border p-6"><span className="w-9 h-9 rounded-full bg-royal-50 text-royal-600 font-extrabold inline-flex items-center justify-center">{n}</span><h3 className="mt-4 font-extrabold">{t}</h3><p className="mt-2 text-sm text-muted">{d}</p></div>)}</div></div></section>

<section className="max-w-[1440px] mx-auto px-6 lg:px-10 py-14"><div className="text-center"><Badge>Get Started</Badge><h2 className="mt-3 text-3xl font-extrabold">Get started in four simple steps</h2></div><div className="mt-8 grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{[['01','Create your account','Register once with IHLink.'],['02','Choose your service','Select the platform or service you need.'],['03','Complete your request','Order, subscribe, request a quote or book a service.'],['04','Track and manage','Follow activity, payments and support from your account.']].map(([n,t,d])=><div key={n} className="rounded-2xl border p-6"><p className="text-sm font-extrabold text-royal-600">{n}</p><h3 className="mt-2 font-extrabold">{t}</h3><p className="mt-2 text-sm text-muted">{d}</p></div>)}</div><div className="mt-7 text-center"><Link to="/register"><Button size="lg">Get Started</Button></Link></div></section>

<section className="bg-navy-900 text-white"><div className="max-w-[1440px] mx-auto px-6 lg:px-10 py-14"><div className="text-center"><Badge className="bg-white/10 text-white border-white/20">Technology Areas</Badge><h2 className="mt-3 text-3xl font-extrabold">Built across practical technology disciplines</h2></div><div className="mt-8 grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3">{['Software & Web','Cloud & DevOps','AI & Data','Robotics & Control','IoT & Embedded','Digital Infrastructure'].map(x=><div key={x} className="rounded-xl border border-white/15 bg-white/5 p-4 text-center text-sm font-bold">{x}</div>)}</div></div></section>

<section className="bg-surface border-b border-border"><div className="max-w-[1440px] mx-auto px-6 lg:px-10 py-14"><div className="text-center"><Badge>Who We Serve</Badge><h2 className="mt-3 text-3xl font-extrabold">Solutions for people and organizations</h2></div><div className="mt-8 grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3">{audiences.map(([Icon,t,d])=><div key={t} className="rounded-2xl bg-white border border-border p-5"><Icon className="w-7 h-7 text-royal-600"/><h3 className="mt-3 font-bold">{t}</h3><p className="mt-1 text-xs text-muted">{d}</p></div>)}</div></div></section>

<section className="max-w-[1440px] mx-auto px-6 lg:px-10 py-14"><div className="text-center"><Badge>Why IHLink?</Badge><h2 className="mt-3 text-3xl font-extrabold">One connected ecosystem for practical solutions</h2></div><div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[[ShieldCheck,'Secure & reliable'],[Cog,'Wide range of solutions'],[Headphones,'Professional support'],[Lightbulb,'Innovation driven']].map(([I,t])=>{const Icon=I as typeof ShieldCheck;return <div key={t as string} className="flex gap-3 p-5 rounded-2xl border"><Icon className="w-6 h-6 text-royal-600 shrink-0"/><span className="font-bold">{t as string}</span></div>})}</div></section>

<section className="bg-surface border-y border-border"><div className="max-w-4xl mx-auto px-6 lg:px-10 py-14"><div className="text-center"><Badge>Frequently Asked Questions</Badge><h2 className="mt-3 text-3xl font-extrabold">Common questions about IHLink</h2></div><div className="mt-7 divide-y rounded-2xl border bg-white">{faqs.map(([q,a])=><details key={q} className="group p-5"><summary className="cursor-pointer list-none flex justify-between gap-4 font-bold">{q}<ChevronDown className="w-5 h-5 group-open:rotate-180 transition-transform"/></summary><p className="mt-3 text-sm text-muted">{a}</p></details>)}</div><div className="mt-4 text-center"><Link to="/faq" className="inline-flex items-center gap-1 text-sm font-bold text-royal-600">View all FAQs <ArrowRight className="w-4 h-4"/></Link></div></div></section>

<section className="max-w-[1440px] mx-auto px-6 lg:px-10 py-14"><div className="rounded-3xl bg-gradient-to-r from-navy-900 to-royal-700 p-8 lg:p-12 text-white flex flex-col lg:flex-row lg:items-center justify-between gap-6"><div><h2 className="text-3xl font-extrabold">Not sure where to start?</h2><p className="mt-2 text-blue-100">Tell us what you need and we will direct you to the appropriate IHLink service.</p></div><div className="flex gap-3"><Link to="/contact"><Button size="lg" variant="secondary" className="bg-white text-navy-900">Contact Us</Button></Link><Link to="/services"><Button size="lg">Explore Divisions</Button></Link></div></div></section>

<section className="border-t border-border bg-surface"><div className="max-w-[1440px] mx-auto px-6 lg:px-10 py-16"><div className="max-w-2xl mx-auto rounded-2xl bg-white border border-border shadow-card px-6 py-9 md:px-10 text-center"><h2 className="text-2xl md:text-3xl font-extrabold">Stay Updated</h2><p className="mt-2 text-sm md:text-base text-muted">Subscribe to our newsletter for product updates, tips, and special offers.</p><form className="mt-6 flex flex-col sm:flex-row gap-3 max-w-xl mx-auto" action="/newsletter" method="post"><label htmlFor="corporate-newsletter-email" className="sr-only">Email address</label><input id="corporate-newsletter-email" name="email" type="email" required autoComplete="email" placeholder="Enter your email" className="min-w-0 flex-1 rounded-xl border border-border bg-white px-4 py-3 text-sm outline-none focus:border-royal-500 focus:ring-4 focus:ring-royal-500/10"/><Button type="submit" className="sm:px-7">Subscribe</Button></form></div></div></section>
<ManagedContentSections pageKey="corporate"/></PageShell>}