import { Link } from 'react-router-dom';
import { PageShell } from '@/components/PageShell';
import { Badge } from '@/components/ui/Badge';
import { ArrowRight, Cloud, Cog, Lightbulb } from 'lucide-react';
const divisions=[
 {id:'digital',title:'Digital Services',subtitle:'Connecting People. Enabling Possibilities.',icon:Cloud,items:[['IHLink DataSub','/datasub','Airtime, data, bills and utilities'],['SchoolPro by IHLink','/schoolpro','School management and education technology'],['IHLink Hosting & Domains','/host','Domains, hosting and digital infrastructure']]},
 {id:'technology',title:'Technology & Engineering',subtitle:'Ideas. Development. Real Impact.',icon:Cog,items:[['IHLink Consult','/consult','Software, cloud, AI and technology consulting'],['IHLink Engineering','/engineering','Control, robotics, IoT and instrumentation']]},
 {id:'business',title:'Business & Innovation Centre',subtitle:'Create. Print. Learn. Innovate.',icon:Lightbulb,items:[['IHLink Print & Branding','/print','Print, design and branding'],['IHLink 3D & Fabrication Lab','/fabrication','3D printing, CAD and prototyping'],['IHLink AI & Compute','/compute','AI, data science and compute services'],['IHLink Academy','/academy','Technology and engineering training'],['Digital Business Centre','/business-centre/digital-services','Document and digital business support']]}
] as const;
export function ServicesPage(){return <PageShell product="corporate"><section className="bg-navy-900 text-white"><div className="max-w-[1280px] mx-auto px-6 lg:px-10 py-20"><Badge className="bg-white/10 text-white border-white/20">Our Divisions</Badge><h1 className="mt-5 text-4xl lg:text-6xl font-extrabold">Three Divisions. One IHLink Ecosystem.</h1><p className="mt-5 text-lg text-blue-100 max-w-2xl">Explore the three IHLink divisions and enter the specialist platform that matches what you need.</p></div></section><main className="max-w-[1280px] mx-auto px-6 lg:px-10 py-14 space-y-8">{divisions.map(d=>{const Icon=d.icon;return <section id={d.id} key={d.id} className="scroll-mt-28 rounded-3xl border overflow-hidden"><div className="p-6 bg-slate-50 flex items-center gap-4"><Icon className="w-9 h-9 text-royal-600"/><div><h2 className="text-2xl font-extrabold">{d.title}</h2><p className="text-sm text-muted">{d.subtitle}</p></div></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4 p-5">{d.items.map(([name,href,desc])=><Link key={name} to={href} className="rounded-2xl border p-5 hover:shadow-card transition-shadow"><h3 className="font-extrabold">{name}</h3><p className="mt-2 text-sm text-muted">{desc}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-royal-600">Explore <ArrowRight className="w-4 h-4"/></span></Link>)}</div></section>})}</main></PageShell>}